<?php
// Map landmark Place_ID / name to best Wikipedia search terms
$wikiTitles = [
    // Cairo
    6 => 'Al-Rifa%27i_Mosque',
    8 => 'Al-Azhar_Park',
    11 => 'Bab_Zuweila',
    12 => 'Bab_al-Futuh',
    13 => 'Bab_al-Nasr_(Cairo)',
    14 => 'Mosque_of_Ibn_Tulun',
    15 => 'Gayer-Anderson_Museum',
    16 => 'Coptic_Museum',
    18 => 'Church_of_Saints_Sergius_and_Bacchus',
    19 => 'Ben_Ezra_Synagogue',
    20 => 'Amr_ibn_al-As_Mosque',
    22 => 'Cairo_Opera_House',
    23 => 'Zamalek',
    24 => 'Manial_Palace',
    25 => 'Abdeen_Palace',
    26 => 'Baron_Empain_Palace',
    27 => 'Basilica_of_Our_Lady_of_Heliopolis',
    28 => 'City_of_the_Dead_(Cairo)',
    29 => 'Wadi_Degla_Protectorate',
    30 => 'Al-Hakim_Mosque',
    31 => 'Bayt_Al-Suhaymi',
    32 => 'Qalawun_complex',
    33 => 'Wikala_of_Al_Ghouri',
    34 => 'Qalawun_complex',
    35 => 'Nilometer',
    36 => 'Smart_Village,_Cairo',
    37 => 'Family_Park_(Cairo)',
    38 => 'Point_90_Mall',
    39 => 'Unknown_Soldier_Memorial_(Cairo)',
    40 => 'Talaat_Harb_Street',
    41 => 'Merryland_Park_(Cairo)',
    42 => 'Cave_Church_(Cairo)',
    43 => 'Cairo_University',
    // Giza
    49 => 'Pharaonic_Village',
    52 => 'Bent_Pyramid',
    53 => 'Red_Pyramid',
    54 => 'Mit_Rahina_Museum',
    55 => 'Mall_of_Egypt',
    56 => 'Ski_Egypt',
    57 => 'Dream_Park_(Egypt)',
    58 => 'ZED_Park_(Egypt)',
    // Alexandria
    60 => 'Kom_El_Dikka',
    61 => 'Catacombs_of_Kom_El_Shoqafa',
    62 => 'Pompey%27s_Pillar_(column)',
    63 => 'Stanley_Bridge',
    65 => 'Royal_Jewelry_Museum',
    66 => 'Montaza_Palace',
    // Luxor
    70 => 'Luxor_Museum',
    71 => 'Mummification_Museum',
    72 => 'Luxor_Corniche',
    75 => 'Valley_of_the_Queens',
    77 => 'Colossi_of_Memnon',
    78 => 'Medinet_Habu',
    79 => 'Ramesseum',
    80 => 'Deir_el-Medina',
    81 => 'Tombs_of_the_Nobles_(Luxor)',
    // Aswan
    83 => 'Aswan_Dam',
    84 => 'Unfinished_obelisk',
    85 => 'Nubian_Museum',
    86 => 'Elephantine',
    87 => 'Aga_Khan_Mausoleum',
    88 => 'Kitchener%27s_Island',
    89 => 'Sehel_Island',
    91 => 'Temple_of_Kom_Ombo',
    92 => 'Temple_of_Edfu',
    // Red Sea
    94 => 'Hurghada_Marina',
    95 => 'El_Dahar',
    96 => 'Mahmya_Island',
    97 => 'Giftun_Island',
    98 => 'Sand_City_Hurghada',
    99 => 'Mini_Egypt_Park',
    100 => 'Makadi_Water_World',
    101 => 'Marsa_Mubarak',
    102 => 'Wadi_El_Gemal_National_Park',
    103 => 'Quseir',
    // South Sinai
    106 => 'SOHO_Square_Sharm_El_Sheikh',
    108 => 'Dahab',
    109 => 'Three_Pools',
    112 => 'Colored_Canyon',
    // Matrouh
    115 => 'Shali_Fortress',
];

return $wikiTitles;
