<?php

namespace Database\Seeders;

use App\Models\Hotel;
use Illuminate\Database\Seeder;

class HotelsSeeder extends Seeder
{
    public function run(): void
    {
        $hotels = [
            // ===== CAIRO (13) =====
            [
                'name' => 'Four Seasons Hotel Cairo at Nile Plaza',
                'description' => 'Luxury high-rise overlooking the Nile with a full-service spa, outdoor infinity pool, and refined dining venues.',
                'address' => '1089 Corniche El Nil, Garden City, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.7,
                'region' => 'Cairo',
                'neighborhood' => 'Garden City',
                'lat' => 30.0444,
                'lng' => 31.2232,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Four+Seasons+Hotel+Cairo+at+Nile+Plaza+Cairo',
                'phone' => '+20 2 27918000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.fourseasons.com/cairo/',
            ],
            [
                'name' => 'Four Seasons Hotel Cairo at The First Residence',
                'description' => 'Elegant hotel in Giza with panoramic Nile and Pyramids views, a luxury spa, and multiple restaurants.',
                'address' => '35 Giza Street, Giza, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.6,
                'region' => 'Cairo',
                'neighborhood' => 'Giza',
                'lat' => 30.0270,
                'lng' => 31.2136,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Four+Seasons+Hotel+Cairo+at+The+First+Residence+Cairo',
                'phone' => '+20 2 35671200',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.fourseasons.com/cairofr/',
            ],
            [
                'name' => 'Marriott Mena House, Cairo',
                'description' => 'Historic hotel on the Pyramids plateau with breathtaking Great Pyramid views, lush gardens, and a world-class spa.',
                'address' => '6 Pyramids Road, Giza, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.8,
                'region' => 'Cairo',
                'neighborhood' => 'Giza',
                'lat' => 29.9841,
                'lng' => 31.1303,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Marriott+Mena+House+Cairo+Cairo',
                'phone' => '+20 2 33773222',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle, Garden',
                'website' => 'https://www.marriott.com/en-us/hotels/caieg-marriott-mena-house-cairo/',
            ],
            [
                'name' => 'Cairo Marriott Hotel & Omar Khayyam Casino',
                'description' => 'Opulent palace-style hotel on Gezira Island with vast gardens, a casino, and several international restaurants.',
                'address' => '16 Saray El Gezirah Street, Zamalek, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Cairo',
                'neighborhood' => 'Zamalek',
                'lat' => 30.0635,
                'lng' => 31.2209,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Cairo+Marriott+Hotel+and+Omar+Khayyam+Casino+Cairo',
                'phone' => '+20 2 27283000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Casino',
                'website' => 'https://www.marriott.com/en-us/hotels/caieg-cairo-marriott-hotel-and-omar-khayyam-casino/',
            ],
            [
                'name' => 'InterContinental Cairo Semiramis',
                'description' => 'Iconic riverside hotel on the Nile Corniche with a rooftop pool, wellness centre, and seven dining options.',
                'address' => 'Corniche El Nil, Garden City, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.4,
                'region' => 'Cairo',
                'neighborhood' => 'Garden City',
                'lat' => 30.0417,
                'lng' => 31.2286,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=InterContinental+Cairo+Semiramis+Cairo',
                'phone' => '+20 2 27988000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.ihg.com/intercontinental/hotels/us/en/cairo/caiha/hoteldetail',
            ],
            [
                'name' => 'Kempinski Nile Hotel Cairo',
                'description' => 'Contemporary luxury hotel on the Nile with a rooftop pool, Mediterranean restaurant, and spacious suites.',
                'address' => '12 Ahmed Ragheb Street, Garden City, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Cairo',
                'neighborhood' => 'Garden City',
                'lat' => 30.0350,
                'lng' => 31.2250,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Kempinski+Nile+Hotel+Cairo+Cairo',
                'phone' => '+20 2 27988000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.kempinski.com/en/cairo/nile-hotel',
            ],
            [
                'name' => 'The Nile Ritz-Carlton, Cairo',
                'description' => 'Premier downtown hotel on the Nile Corniche with a grand pool, luxury spa, and exquisite dining.',
                'address' => '1113 Corniche El Nil, Downtown, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.6,
                'region' => 'Cairo',
                'neighborhood' => 'Downtown',
                'lat' => 30.0448,
                'lng' => 31.2281,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=The+Nile+Ritz-Carlton+Cairo+Cairo',
                'phone' => '+20 2 25778844',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.ritzcarlton.com/en/hotels/cairo',
            ],
            [
                'name' => 'Fairmont Nile City',
                'description' => 'Modern five-star hotel in the Nile City Towers with a rooftop pool, cigar lounge, and panoramic Nile views.',
                'address' => 'Nile City Towers, 2005B Corniche El Nil, Ramlet Boulaq, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.4,
                'region' => 'Cairo',
                'neighborhood' => 'Ramlet Boulaq',
                'lat' => 30.0700,
                'lng' => 31.2250,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Fairmont+Nile+City+Cairo',
                'phone' => '+20 2 24619400',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.fairmont.com/nile-city/',
            ],
            [
                'name' => 'Conrad Cairo',
                'description' => 'Sleek business hotel on the Nile Corniche offering contemporary rooms, a casino, and multiple dining venues.',
                'address' => '1191 Corniche El Nil, Downtown, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.3,
                'region' => 'Cairo',
                'neighborhood' => 'Downtown',
                'lat' => 30.0470,
                'lng' => 31.2290,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Conrad+Cairo+Cairo',
                'phone' => '+20 2 25808000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle, Casino',
                'website' => 'https://www.hilton.com/en/hotels/caicici-conrad-cairo/',
            ],
            [
                'name' => 'Grand Nile Tower',
                'description' => 'Towering landmark hotel on the Nile featuring a revolving restaurant, multiple pools, and a spa.',
                'address' => 'Corniche El Nil, Garden City, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.2,
                'region' => 'Cairo',
                'neighborhood' => 'Garden City',
                'lat' => 30.0410,
                'lng' => 31.2240,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Grand+Nile+Tower+Cairo',
                'phone' => '+20 2 27985000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.grandniletower.com/',
            ],
            [
                'name' => 'Sofitel Cairo Nile El Gezirah',
                'description' => 'Art-deco inspired hotel on Gezira Island with panoramic Nile views and an exclusive spa.',
                'address' => '3 El Thawra Council Street, Zamalek, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Cairo',
                'neighborhood' => 'Zamalek',
                'lat' => 30.0620,
                'lng' => 31.2180,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Sofitel+Cairo+Nile+El+Gezirah+Cairo',
                'phone' => '+20 2 27369900',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.sofitel.com/hotel/1093-sofitel-cairo-nile-el-gezirah',
            ],
            [
                'name' => 'Steigenberger Hotel El Tahrir Cairo',
                'description' => 'Design-oriented hotel in the heart of Cairo near Tahrir Square with a rooftop pool and vibrant lounge.',
                'address' => '2 Kasr El Nil Street, Downtown, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.3,
                'region' => 'Cairo',
                'neighborhood' => 'Downtown',
                'lat' => 30.0460,
                'lng' => 31.2350,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Steigenberger+Hotel+El+Tahrir+Cairo+Cairo',
                'phone' => '+20 2 25773311',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking',
                'website' => 'https://www.steigenberger.com/en/hotels/egypt/cairo/steigenberger-hotel-el-tahrir',
            ],
            [
                'name' => 'Ramses Hilton',
                'description' => 'Landmark Cairo hotel on the Nile with a large pool, casino, and direct access to downtown attractions.',
                'address' => '1115 Corniche El Nil, Downtown, Cairo',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.1,
                'region' => 'Cairo',
                'neighborhood' => 'Downtown',
                'lat' => 30.0501,
                'lng' => 31.2299,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Ramses+Hilton+Cairo+Cairo',
                'phone' => '+20 2 25747400',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Casino',
                'website' => 'https://www.hilton.com/en/hotels/cairhhi-ramses-hilton/',
            ],

            // ===== ALEXANDRIA (5) =====
            [
                'name' => 'Four Seasons Hotel Alexandria at San Stefano',
                'description' => 'Beachfront luxury resort with a private marina, outdoor pool, and exceptional Mediterranean dining.',
                'address' => '399 El Geish Road, San Stefano, Alexandria',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.7,
                'region' => 'Alexandria',
                'neighborhood' => 'San Stefano',
                'lat' => 31.2400,
                'lng' => 29.9640,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Four+Seasons+Hotel+Alexandria+at+San+Stefano+Alexandria',
                'phone' => '+20 3 5818000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.fourseasons.com/alexandria/',
            ],
            [
                'name' => 'Hilton Alexandria Corniche',
                'description' => 'Seaside hotel on the Corniche with a large outdoor pool, fitness centre, and panoramic Mediterranean sea views.',
                'address' => 'Saad Zaghloul Square, Raml Station, Alexandria',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.3,
                'region' => 'Alexandria',
                'neighborhood' => 'Raml Station',
                'lat' => 31.2000,
                'lng' => 29.9050,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Hilton+Alexandria+Corniche+Alexandria',
                'phone' => '+20 3 4808880',
                'amenities' => 'Pool, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.hilton.com/en/hotels/alyalhhi-hilton-alexandria-corniche/',
            ],
            [
                'name' => 'Sheraton Alexandria Montazah Hotel',
                'description' => 'Resort-style hotel adjacent to Montazah Palace Gardens with a private beach and marina views.',
                'address' => 'Corniche El Geish, Montazah, Alexandria',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.2,
                'region' => 'Alexandria',
                'neighborhood' => 'Montazah',
                'lat' => 31.2800,
                'lng' => 29.9950,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Sheraton+Alexandria+Montazah+Hotel+Alexandria',
                'phone' => '+20 3 4759800',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.marriott.com/en-us/hotels/alysm-sheraton-alexandria-montazah-hotel/',
            ],
            [
                'name' => 'Steigenberger Cecil Hotel Alexandria',
                'description' => 'Historic colonial-era landmark hotel on the Corniche steps from Bibliotheca Alexandrina.',
                'address' => '16 Saad Zaghloul Square, Raml Station, Alexandria',
                'category' => 'Hotel',
                'star_rating' => 4,
                'price_level' => '$$',
                'rating' => 4.2,
                'region' => 'Alexandria',
                'neighborhood' => 'Raml Station',
                'lat' => 31.1980,
                'lng' => 29.9040,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Steigenberger+Cecil+Hotel+Alexandria+Alexandria',
                'phone' => '+20 3 4877173',
                'amenities' => 'Restaurant, Free WiFi, Parking, Gym',
                'website' => 'https://www.steigenberger.com/en/hotels/egypt/alexandria/steigenberger-cecil-hotel',
            ],
            [
                'name' => 'Le Métropole Hotel Alexandria',
                'description' => 'Vintage Belle Époque hotel overlooking the Eastern Harbour with period furnishings and old-world allure.',
                'address' => '52 Saad Zaghloul Street, Raml Station, Alexandria',
                'category' => 'Boutique Hotel',
                'star_rating' => 4,
                'price_level' => '$$',
                'rating' => 4.0,
                'region' => 'Alexandria',
                'neighborhood' => 'Raml Station',
                'lat' => 31.1985,
                'lng' => 29.9020,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Le+Metropole+Hotel+Alexandria+Alexandria',
                'phone' => '+20 3 4861465',
                'amenities' => 'Restaurant, Free WiFi, Parking',
                'website' => null,
            ],

            // ===== LUXOR (6) =====
            [
                'name' => 'Sofitel Winter Palace Luxor',
                'description' => 'Historic Victorian palace hotel on the Nile Corniche with lush gardens and old-world grandeur.',
                'address' => 'Corniche El Nil, East Bank, Luxor',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.6,
                'region' => 'Luxor',
                'neighborhood' => 'East Bank',
                'lat' => 25.7000,
                'lng' => 32.6390,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Sofitel+Winter+Palace+Luxor+Luxor',
                'phone' => '+20 95 2380422',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Garden',
                'website' => 'https://www.sofitel.com/hotel/0809-sofitel-luxor-winter-palace',
            ],
            [
                'name' => 'Hilton Luxor Resort & Spa',
                'description' => 'Contemporary Nile-side resort near the Temple of Karnak with a large free-form pool and spa.',
                'address' => 'New Karnak, Karnak, Luxor',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Luxor',
                'neighborhood' => 'Karnak',
                'lat' => 25.7180,
                'lng' => 32.6580,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Hilton+Luxor+Resort+and+Spa+Luxor',
                'phone' => '+20 95 2274933',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle, Beach Access',
                'website' => 'https://www.hilton.com/en/hotels/lxrlxhi-hilton-luxor-resort/',
            ],
            [
                'name' => 'Steigenberger Nile Palace Luxor',
                'description' => 'Modern hotel on the Nile with a rooftop pool, international dining, and proximity to the Valley of the Kings.',
                'address' => 'Khaled Ibn El Walid Street, East Bank, Luxor',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.4,
                'region' => 'Luxor',
                'neighborhood' => 'East Bank',
                'lat' => 25.6930,
                'lng' => 32.6420,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Steigenberger+Nile+Palace+Luxor+Luxor',
                'phone' => '+20 95 2366999',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.steigenberger.com/en/hotels/egypt/luxor/steigenberger-nile-palace',
            ],
            [
                'name' => 'Pavillon Winter Luxor',
                'description' => 'Garden-front wing of the Winter Palace offering relaxed accommodation with pool access.',
                'address' => 'Corniche El Nil, East Bank, Luxor',
                'category' => 'Hotel',
                'star_rating' => 4,
                'price_level' => '$$',
                'rating' => 4.3,
                'region' => 'Luxor',
                'neighborhood' => 'East Bank',
                'lat' => 25.7005,
                'lng' => 32.6395,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Pavillon+Winter+Luxor+Luxor',
                'phone' => '+20 95 2380422',
                'amenities' => 'Pool, Restaurant, Free WiFi, Parking, Garden',
                'website' => 'https://www.sofitel.com/hotel/0809-sofitel-luxor-winter-palace',
            ],
            [
                'name' => 'Mercure Luxor Karnak',
                'description' => 'Tranquil resort near Karnak Temple with lush gardens, multiple pools, and Nile views.',
                'address' => 'El Karnak Street, Karnak, Luxor',
                'category' => 'Resort',
                'star_rating' => 4,
                'price_level' => '$$',
                'rating' => 4.1,
                'region' => 'Luxor',
                'neighborhood' => 'Karnak',
                'lat' => 25.7150,
                'lng' => 32.6550,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Mercure+Luxor+Karnak+Luxor',
                'phone' => '+20 95 2274993',
                'amenities' => 'Pool, Restaurant, Free WiFi, Parking, Garden',
                'website' => 'https://www.accor.com/hotel/0813',
            ],
            [
                'name' => 'Al Moudira Hotel',
                'description' => 'Orientalist boutique hotel on the West Bank with domed architecture, a pool, and lush gardens.',
                'address' => 'West Bank, Luxor',
                'category' => 'Boutique Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.7,
                'region' => 'Luxor',
                'neighborhood' => 'West Bank',
                'lat' => 25.6950,
                'lng' => 32.5950,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Al+Moudira+Hotel+Luxor+Luxor',
                'phone' => '+20 95 2310005',
                'amenities' => 'Pool, Restaurant, Free WiFi, Parking, Garden',
                'website' => 'https://www.moudira.com/',
            ],

            // ===== ASWAN (5) =====
            [
                'name' => 'Sofitel Legend Old Cataract Aswan',
                'description' => 'Historic riverside hotel on the Nile with Victorian architecture, lush gardens, and views of Elephantine Island.',
                'address' => 'Abtal El Tahrir Street, Aswan',
                'category' => 'Hotel',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.8,
                'region' => 'Aswan',
                'neighborhood' => 'Aswan City',
                'lat' => 24.0790,
                'lng' => 32.8870,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Sofitel+Legend+Old+Cataract+Aswan+Aswan',
                'phone' => '+20 97 2316000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.sofitel.com/hotel/0805-sofitel-legend-old-cataract',
            ],
            [
                'name' => 'Mövenpick Resort Aswan',
                'description' => 'Resort on Elephantine Island accessible by complimentary boat with panoramic Nile vistas.',
                'address' => 'Elephantine Island, Aswan',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.4,
                'region' => 'Aswan',
                'neighborhood' => 'Elephantine Island',
                'lat' => 24.0860,
                'lng' => 32.8870,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Movenpick+Resort+Aswan+Aswan',
                'phone' => '+20 97 2303455',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.movenpick.com/en/africa/egypt/aswan/movenpick-resort-aswan/',
            ],
            [
                'name' => 'Pyramisa Isis Island Aswan Resort',
                'description' => 'Tropical island resort on the Nile with multiple pools, a spa, and lush landscaped gardens.',
                'address' => 'Isis Island, Aswan',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.2,
                'region' => 'Aswan',
                'neighborhood' => 'Isis Island',
                'lat' => 24.0780,
                'lng' => 32.8930,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Pyramisa+Isis+Island+Aswan+Resort+Aswan',
                'phone' => '+20 97 2317400',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Free WiFi, Parking, Airport Shuttle',
                'website' => 'http://www.pyramisaegypt.com/',
            ],
            [
                'name' => 'Basma Hotel Aswan',
                'description' => 'Mid-range hilltop hotel offering sweeping Nile views and a large free-form pool.',
                'address' => 'El Fanadek Street, Aswan',
                'category' => 'Hotel',
                'star_rating' => 4,
                'price_level' => '$$',
                'rating' => 4.0,
                'region' => 'Aswan',
                'neighborhood' => 'Aswan City',
                'lat' => 24.0810,
                'lng' => 32.8910,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Basma+Hotel+Aswan+Aswan',
                'phone' => '+20 97 2483001',
                'amenities' => 'Pool, Restaurant, Free WiFi, Parking',
                'website' => 'https://www.basmahotel.com/',
            ],
            [
                'name' => 'Citymax Hotel Aswan',
                'description' => 'Modern budget-friendly hotel on the Corniche with clean rooms and a rooftop restaurant.',
                'address' => 'Corniche El Nil, Aswan',
                'category' => 'Hotel',
                'star_rating' => 3,
                'price_level' => '$',
                'rating' => 4.0,
                'region' => 'Aswan',
                'neighborhood' => 'Aswan City',
                'lat' => 24.0770,
                'lng' => 32.8850,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Citymax+Hotel+Aswan+Aswan',
                'phone' => '+20 97 2484000',
                'amenities' => 'Restaurant, Free WiFi, Parking',
                'website' => 'https://www.citymaxhotels.com/',
            ],

            // ===== HURGHADA (7) =====
            [
                'name' => 'Steigenberger Al Dau Beach Hotel',
                'description' => 'Upscale beachfront resort with a large pool complex, private beach, and multiple dining venues.',
                'address' => 'El Corniche Road, Hurghada',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.6,
                'region' => 'Hurghada',
                'neighborhood' => 'El Corniche',
                'lat' => 27.2500,
                'lng' => 33.8200,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Steigenberger+Al+Dau+Beach+Hotel+Hurghada',
                'phone' => '+20 65 3465400',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.steigenberger.com/en/hotels/egypt/hurghada/steigenberger-al-dau-beach-hotel',
            ],
            [
                'name' => 'Hilton Hurghada Plaza',
                'description' => 'Beachfront resort on the Red Sea with a lagoon pool, dive centre, and international buffet.',
                'address' => 'El Corniche Road, Hurghada',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.4,
                'region' => 'Hurghada',
                'neighborhood' => 'El Corniche',
                'lat' => 27.2400,
                'lng' => 33.8300,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Hilton+Hurghada+Plaza+Hurghada',
                'phone' => '+20 65 3465000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking, Airport Shuttle',
                'website' => 'https://www.hilton.com/en/hotels/hrgplhi-hilton-hurghada-plaza/',
            ],
            [
                'name' => 'Hurghada Marriott Beach Resort',
                'description' => 'Sprawling beach resort with a huge pool, private beach, spa, and several bars and restaurants.',
                'address' => 'El Corniche Road, Hurghada',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Hurghada',
                'neighborhood' => 'El Corniche',
                'lat' => 27.2280,
                'lng' => 33.8450,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Hurghada+Marriott+Beach+Resort+Hurghada',
                'phone' => '+20 65 3449100',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.marriott.com/en-us/hotels/hrgbr-hurghada-marriott-beach-resort/',
            ],
            [
                'name' => 'Jaz Aquaviva Resort',
                'description' => 'All-inclusive resort with one of the largest water parks in the region and multiple pools.',
                'address' => 'Safaga Road, Hurghada',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.6,
                'region' => 'Hurghada',
                'neighborhood' => 'Safaga Road',
                'lat' => 27.2000,
                'lng' => 33.8600,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Jaz+Aquaviva+Resort+Hurghada',
                'phone' => '+20 65 3490000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking, Water Park',
                'website' => 'https://www.jazhotels.com/',
            ],
            [
                'name' => 'Pickalbatros Palace Resort',
                'description' => 'Italian-themed resort with a water park, private beach, and all-inclusive dining.',
                'address' => 'Safaga Road, Hurghada',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Hurghada',
                'neighborhood' => 'Safaga Road',
                'lat' => 27.1850,
                'lng' => 33.8700,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Pickalbatros+Palace+Resort+Hurghada',
                'phone' => '+20 65 3490900',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking, Water Park',
                'website' => 'https://www.pickalbatros.com/',
            ],
            [
                'name' => 'Mercure Hurghada Hotel',
                'description' => 'Beachfront hotel in the heart of Hurghada with a dive centre, pool, and easy access to the promenade.',
                'address' => 'El Corniche Road, Hurghada',
                'category' => 'Hotel',
                'star_rating' => 4,
                'price_level' => '$$',
                'rating' => 4.0,
                'region' => 'Hurghada',
                'neighborhood' => 'El Corniche',
                'lat' => 27.2550,
                'lng' => 33.8150,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Mercure+Hurghada+Hotel+Hurghada',
                'phone' => '+20 65 3465070',
                'amenities' => 'Pool, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.accor.com/hotel/1798',
            ],
            [
                'name' => 'Sunrise Royal Makadi Resort',
                'description' => 'All-inclusive resort on Makadi Bay with a water park, private beach, and multiple swimming pools.',
                'address' => 'Makadi Bay, Hurghada',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.7,
                'region' => 'Hurghada',
                'neighborhood' => 'Makadi Bay',
                'lat' => 26.9800,
                'lng' => 33.9100,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Sunrise+Royal+Makadi+Resort+Hurghada',
                'phone' => '+20 65 3550000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking, Water Park',
                'website' => 'https://www.sunrise-resorts.com/',
            ],

            // ===== SHARM EL-SHEIKH (6) =====
            [
                'name' => 'Four Seasons Resort Sharm El Sheikh',
                'description' => 'Exclusive resort on a private beach with lush gardens, a golf academy, and world-class diving.',
                'address' => '1 Four Seasons Boulevard, Sharm El Sheikh',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.8,
                'region' => 'Sharm El-Sheikh',
                'neighborhood' => 'Ras Nasrani',
                'lat' => 27.8800,
                'lng' => 34.3100,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Four+Seasons+Resort+Sharm+El+Sheikh+Sharm+El+Sheikh',
                'phone' => '+20 69 3603555',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.fourseasons.com/sharmelsheikh/',
            ],
            [
                'name' => 'Rixos Sharm El Sheikh',
                'description' => 'Ultra all-inclusive resort with a private beach, multiple pools, and a vibrant entertainment programme.',
                'address' => 'El Salam Road, Naama Bay, Sharm El Sheikh',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.6,
                'region' => 'Sharm El-Sheikh',
                'neighborhood' => 'Naama Bay',
                'lat' => 27.9150,
                'lng' => 34.3350,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Rixos+Sharm+El+Sheikh+Sharm+El+Sheikh',
                'phone' => '+20 69 3603000',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.rixos.com/en/hotel-resort/rixos-sharm-el-sheikh',
            ],
            [
                'name' => 'Hilton Sharm El Sheikh Fayrouz Resort',
                'description' => 'Family-friendly resort on the promenade with a dolphin enclosure, water sports, and sea views.',
                'address' => 'Naama Bay, Sharm El Sheikh',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.3,
                'region' => 'Sharm El-Sheikh',
                'neighborhood' => 'Naama Bay',
                'lat' => 27.9100,
                'lng' => 34.3300,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Hilton+Sharm+El+Sheikh+Fayrouz+Resort+Sharm+El+Sheikh',
                'phone' => '+20 69 3600133',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.hilton.com/en/hotels/sshfahi-hilton-sharm-el-sheikh-fayrouz-resort/',
            ],
            [
                'name' => 'Savoy Sharm El Sheikh',
                'description' => 'Elegant resort in Soho Square with a private beach, large lagoon pool, and duty-free shopping access.',
                'address' => 'Soho Square, Sharm El Sheikh',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Sharm El-Sheikh',
                'neighborhood' => 'Soho Square',
                'lat' => 27.8900,
                'lng' => 34.2950,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Savoy+Sharm+El+Sheikh+Sharm+El+Sheikh',
                'phone' => '+20 69 3602500',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.savoyegypt.com/',
            ],
            [
                'name' => 'Baron Palace Sharm El Sheikh',
                'description' => 'Opulent resort with a massive pool complex, private beach, and extensive spa facilities.',
                'address' => 'Hadaba, Sharm El Sheikh',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.4,
                'region' => 'Sharm El-Sheikh',
                'neighborhood' => 'Hadaba',
                'lat' => 27.8600,
                'lng' => 34.2900,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Baron+Palace+Sharm+El+Sheikh+Sharm+El+Sheikh',
                'phone' => '+20 69 3660888',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.baronpalacesharm.com/',
            ],
            [
                'name' => 'Stella Di Mare Beach Hotel & Spa',
                'description' => 'Italian-inspired resort with a private beach, thalasso spa, and gourmet dining on the Red Sea.',
                'address' => 'El Montazah, Sharm El Sheikh',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Sharm El-Sheikh',
                'neighborhood' => 'El Montazah',
                'lat' => 27.8750,
                'lng' => 34.2800,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Stella+Di+Mare+Beach+Hotel+and+Spa+Sharm+El+Sheikh',
                'phone' => '+20 69 3664999',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.stelladimare.com/',
            ],

            // ===== EL GOUNA / DAHAB / MARSA ALAM / SIWA (6) =====
            [
                'name' => 'Mövenpick Resort El Gouna',
                'description' => 'Waterfront resort on the El Gouna lagoons with a private beach, multiple pools, and a marina.',
                'address' => 'El Gouna, Red Sea',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'El Gouna',
                'neighborhood' => 'El Gouna',
                'lat' => 27.3900,
                'lng' => 33.6800,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Movenpick+Resort+El+Gouna+El+Gouna',
                'phone' => '+20 65 3540800',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.movenpick.com/en/africa/egypt/el-gouna/movenpick-resort-el-gouna/',
            ],
            [
                'name' => 'The Chedi El Gouna',
                'description' => 'Contemporary minimalist resort with Asian-inspired design, a lagoon pool, and a private beach.',
                'address' => 'El Gouna, Red Sea',
                'category' => 'Resort',
                'star_rating' => 5,
                'price_level' => '$$$',
                'rating' => 4.7,
                'region' => 'El Gouna',
                'neighborhood' => 'El Gouna',
                'lat' => 27.3950,
                'lng' => 33.6850,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=The+Chedi+El+Gouna+El+Gouna',
                'phone' => '+20 65 3545100',
                'amenities' => 'Pool, Spa, Gym, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.ghmhotels.com/en/chedi-el-gouna/',
            ],
            [
                'name' => 'La Maison Bleue Dahab',
                'description' => 'Charming boutique hotel on the Dahab seafront with an art gallery, courtyard, and sea-view rooms.',
                'address' => 'Mashraba Street, Dahab',
                'category' => 'Boutique Hotel',
                'star_rating' => 4,
                'price_level' => '$$',
                'rating' => 4.6,
                'region' => 'Dahab',
                'neighborhood' => 'Mashraba',
                'lat' => 28.4930,
                'lng' => 34.5050,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=La+Maison+Bleue+Dahab+Dahab',
                'phone' => '+20 69 3641506',
                'amenities' => 'Restaurant, Free WiFi, Beach Access',
                'website' => 'https://www.lamaisonbleue.com/',
            ],
            [
                'name' => 'Adulis Marsa Alam',
                'description' => 'Tranquil eco-resort on the Red Sea coast with coral reefs, a spa, and beachfront bungalows.',
                'address' => 'Quseir - Marsa Alam Road, Marsa Alam',
                'category' => 'Resort',
                'star_rating' => 4,
                'price_level' => '$$',
                'rating' => 4.4,
                'region' => 'Marsa Alam',
                'neighborhood' => 'Marsa Alam Coast',
                'lat' => 25.0700,
                'lng' => 34.8900,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Adulis+Marsa+Alam+Marsa+Alam',
                'phone' => '+20 65 3700100',
                'amenities' => 'Pool, Spa, Restaurant, Beach Access, Free WiFi, Parking',
                'website' => 'https://www.adulisresort.com/',
            ],
            [
                'name' => 'Siwa Shali Resort',
                'description' => 'Eco-friendly desert lodge built from local materials overlooking the ancient Shali Fortress.',
                'address' => 'Siwa Oasis, Matrouh Governorate',
                'category' => 'Lodge',
                'star_rating' => 4,
                'price_level' => '$$',
                'rating' => 4.3,
                'region' => 'Siwa',
                'neighborhood' => 'Siwa City',
                'lat' => 29.2000,
                'lng' => 25.5200,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Siwa+Shali+Resort+Siwa',
                'phone' => '+20 46 9200110',
                'amenities' => 'Pool, Restaurant, Free WiFi, Parking, Garden',
                'website' => null,
            ],
            [
                'name' => 'Taziry Ecolodge Siwa',
                'description' => 'Secluded eco-lodge on the Siwa salt lake with adobe domed rooms, organic dining, and stargazing.',
                'address' => 'Siwa Oasis, Matrouh Governorate',
                'category' => 'Lodge',
                'star_rating' => 4,
                'price_level' => '$$',
                'rating' => 4.5,
                'region' => 'Siwa',
                'neighborhood' => 'Siwa Desert',
                'lat' => 29.1800,
                'lng' => 25.4800,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Taziry+Ecolodge+Siwa+Siwa',
                'phone' => '+20 46 9156172',
                'amenities' => 'Pool, Restaurant, Parking, Garden',
                'website' => 'https://www.taziry.com/',
            ],
        ];

        foreach ($hotels as $data) {
            Hotel::updateOrCreate(
                ['name' => $data['name']],
                $data
            );
        }
    }
}
