<?php

namespace Database\Seeders;

use App\Models\Restaurant;
use Illuminate\Database\Seeder;

class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            // ─── Cairo ──────────────────────────────────────────────
            [
                'name' => 'Abou El Sid',
                'description' => 'Upscale Egyptian restaurant serving classic dishes like molokhiya, stuffed pigeon, and mixed grills in a warm, rustic setting.',
                'address' => '157 26th July St, Zamalek, Cairo',
                'category' => 'Egyptian',
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Cairo',
                'lat' => 30.0644,
                'lng' => 31.2192,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Abou+El+Sid+Zamalek+Cairo',
                'image' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5',
                'phone' => '+20 2 2735 9640',
                'opening_hours' => '12:00 PM – 12:00 AM',
            ],
            [
                'name' => 'Kazaz Restaurant',
                'description' => 'Famous for its Egyptian street food — best hawawshi and grilled liver sandwiches in town.',
                'address' => '26 Adly St, Downtown, Cairo',
                'category' => 'Egyptian',
                'price_level' => '$',
                'rating' => 4.3,
                'region' => 'Cairo',
                'lat' => 30.0488,
                'lng' => 31.2362,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Kazaz+Restaurant+Downtown+Cairo',
                'image' => null,
                'phone' => '+20 2 2393 1574',
                'opening_hours' => '9:00 AM – 11:00 PM',
            ],
            [
                'name' => 'Zooba',
                'description' => 'Modern Egyptian street food chain with a trendy twist on classics like koshari, falafel, and ful.',
                'address' => '22 26th July St, Zamalek, Cairo',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.4,
                'region' => 'Cairo',
                'lat' => 30.0649,
                'lng' => 31.2198,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Zooba+Zamalek+Cairo',
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
                'phone' => '+20 2 2736 0065',
                'opening_hours' => '8:00 AM – 11:00 PM',
            ],
            [
                'name' => 'The Smokery',
                'description' => 'Chic waterfront restaurant in Zamalek serving fresh seafood, steaks, and international dishes with Nile views.',
                'address' => '26th July St, Zamalek, Cairo',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.6,
                'region' => 'Cairo',
                'lat' => 30.0655,
                'lng' => 31.2185,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=The+Smokery+Zamalek+Cairo',
                'image' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
                'phone' => '+20 2 2736 4560',
                'opening_hours' => '12:00 PM – 1:00 AM',
            ],
            [
                'name' => 'Felfela',
                'description' => 'A Cairo institution since 1959, famous for its falafel, ful medames, and authentic Egyptian breakfasts.',
                'address' => '15 Hoda Shaarawi St, Downtown, Cairo',
                'category' => 'Egyptian',
                'price_level' => '$',
                'rating' => 4.2,
                'region' => 'Cairo',
                'lat' => 30.0496,
                'lng' => 31.2375,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Felfela+Downtown+Cairo',
                'image' => null,
                'phone' => '+20 2 2393 2833',
                'opening_hours' => '7:00 AM – 11:00 PM',
            ],
            [
                'name' => 'Sabaya',
                'description' => 'Lebanese fine-dining restaurant at the Four Seasons, offering mezze, grilled meats, and stunning Nile vistas.',
                'address' => 'Four Seasons Hotel, Garden City, Cairo',
                'category' => 'Lebanese',
                'price_level' => '$$$',
                'rating' => 4.7,
                'region' => 'Cairo',
                'lat' => 30.0386,
                'lng' => 31.2247,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Sabaya+Four+Seasons+Cairo',
                'image' => null,
                'phone' => '+20 2 2791 7000',
                'opening_hours' => '6:00 PM – 12:00 AM',
            ],
            [
                'name' => 'Khan El Khalili Restaurant',
                'description' => 'Historic restaurant inside the famous bazaar — perfect for grilled meats, Egyptian mezza, and mint tea after shopping.',
                'address' => 'Khan El Khalili, Al-Azhar St, Cairo',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.0,
                'region' => 'Cairo',
                'lat' => 30.0478,
                'lng' => 31.2627,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Khan+El+Khalili+Restaurant+Cairo',
                'image' => null,
                'phone' => '+20 2 2590 3788',
                'opening_hours' => '9:00 AM – 11:00 PM',
            ],
            [
                'name' => 'Osmanly Restaurant',
                'description' => 'Ottoman-Turkish cuisine in a grand setting inside the Cairo Marriott, known for lamb dishes and baklava.',
                'address' => 'Cairo Marriott Hotel, Zamalek, Cairo',
                'category' => 'Turkish',
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Cairo',
                'lat' => 30.0640,
                'lng' => 31.2170,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Osmanly+Restaurant+Zamalek+Cairo',
                'image' => null,
                'phone' => '+20 2 2728 3000',
                'opening_hours' => '6:00 PM – 11:00 PM',
            ],
            [
                'name' => 'Maison Thomas',
                'description' => 'Cairo oldest pizzeria since 1925, serving thin-crust pizzas baked in a wood-fired oven with classic Italian toppings.',
                'address' => '12 Brazil St, Zamalek, Cairo',
                'category' => 'Italian',
                'price_level' => '$$',
                'rating' => 4.3,
                'region' => 'Cairo',
                'lat' => 30.0640,
                'lng' => 31.2155,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Maison+Thomas+Zamalek+Cairo',
                'image' => null,
                'phone' => '+20 2 2735 7055',
                'opening_hours' => '10:00 AM – 11:30 PM',
            ],
            [
                'name' => 'Crave',
                'description' => 'Trendy all-day dining spot in Zamalek offering creative international dishes, gourmet burgers, and artisanal cocktails.',
                'address' => '21 Amman St, Zamalek, Cairo',
                'category' => 'International',
                'price_level' => '$$',
                'rating' => 4.4,
                'region' => 'Cairo',
                'lat' => 30.0648,
                'lng' => 31.2140,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Crave+Zamalek+Cairo',
                'image' => null,
                'phone' => '+20 2 2735 6700',
                'opening_hours' => '9:00 AM – 12:00 AM',
            ],
            [
                'name' => 'Sequoia',
                'description' => 'Lush garden restaurant on the Nile bank with a relaxed vibe, serving international cuisine and shisha under the trees.',
                'address' => 'Abu El Feda St, Zamalek, Cairo',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Cairo',
                'lat' => 30.0665,
                'lng' => 31.2170,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Sequoia+Zamalek+Cairo',
                'image' => null,
                'phone' => '+20 2 2735 0010',
                'opening_hours' => '12:00 PM – 2:00 AM',
            ],
            [
                'name' => 'Cairo Kitchen',
                'description' => 'Farm-to-table Egyptian concept reimagining grandma recipes with modern presentation and organic ingredients.',
                'address' => '23 Ismail Mohammed St, Zamalek, Cairo',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.2,
                'region' => 'Cairo',
                'lat' => 30.0635,
                'lng' => 31.2165,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Cairo+Kitchen+Zamalek',
                'image' => null,
                'phone' => '+20 2 2736 7788',
                'opening_hours' => '9:00 AM – 11:00 PM',
            ],
            [
                'name' => 'Tabla',
                'description' => 'Contemporary Egyptian restaurant in Zamalek known for its inventive twists on traditional Egyptian street food.',
                'address' => '13 Shagaret Al Dorr St, Zamalek, Cairo',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.3,
                'region' => 'Cairo',
                'lat' => 30.0652,
                'lng' => 31.2138,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Tabla+Zamalek+Cairo',
                'image' => null,
                'phone' => '+20 2 2736 2244',
                'opening_hours' => '12:00 PM – 11:30 PM',
            ],
            [
                'name' => 'La Bodega',
                'description' => 'Classic downtown bistro and bar known for its grilled meats, seafood, and vibrant nightlife scene.',
                'address' => '157 Hoda Shaarawi St, Downtown, Cairo',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.1,
                'region' => 'Cairo',
                'lat' => 30.0480,
                'lng' => 31.2380,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=La+Bodega+Downtown+Cairo',
                'image' => null,
                'phone' => '+20 2 2392 7701',
                'opening_hours' => '12:00 PM – 2:00 AM',
            ],
            [
                'name' => 'Estoula',
                'description' => 'Charming Egyptian-Greek restaurant in Maadi with a sunny terrace and authentic wood-fired dishes.',
                'address' => '22 El-Nasr St, Maadi, Cairo',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.4,
                'region' => 'Cairo',
                'lat' => 29.9630,
                'lng' => 31.2540,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Estoula+Maaadi+Cairo',
                'image' => null,
                'phone' => '+20 2 2359 1919',
                'opening_hours' => '1:00 PM – 11:00 PM',
            ],
            [
                'name' => 'Mosaic Restaurant',
                'description' => 'Elegant oriental and international buffet restaurant in Maadi offering live cooking stations and nightly entertainment.',
                'address' => '51 Palestine Rd, Maadi, Cairo',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.0,
                'region' => 'Cairo',
                'lat' => 29.9600,
                'lng' => 31.2570,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Mosaic+Restaurant+Maaadi+Cairo',
                'image' => null,
                'phone' => '+20 2 2358 6655',
                'opening_hours' => '6:30 AM – 11:00 PM',
            ],
            [
                'name' => 'Sangria',
                'description' => 'Vibrant Latin-American restaurant and bar in Zamalek famous for its tapas, grilled meats, and signature cocktails.',
                'address' => '21 Abou El Feda St, Zamalek, Cairo',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.2,
                'region' => 'Cairo',
                'lat' => 30.0660,
                'lng' => 31.2180,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Sangria+Zamalek+Cairo',
                'image' => null,
                'phone' => '+20 2 2735 0077',
                'opening_hours' => '5:00 PM – 2:00 AM',
            ],
            [
                'name' => 'Revolving Restaurant',
                'description' => 'Cairo iconic revolving restaurant atop the Cairo Tower offering 360-degree panoramic views and international buffet.',
                'address' => 'Cairo Tower, Zamalek, Cairo',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.1,
                'region' => 'Cairo',
                'lat' => 30.0490,
                'lng' => 31.2245,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Revolving+Restaurant+Cairo+Tower',
                'image' => null,
                'phone' => '+20 2 2736 5112',
                'opening_hours' => '12:00 PM – 11:00 PM',
            ],
            // ─── Giza (Pyramids area) ───────────────────────────────
            [
                'name' => 'Pyramids Restaurant',
                'description' => 'Rooftop dining with a direct view of the Giza Pyramids — serves Egyptian grilled dishes and mezza.',
                'address' => 'Pyramids Plateau, Giza',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.1,
                'region' => 'Giza',
                'lat' => 29.9792,
                'lng' => 31.1342,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Pyramids+Restaurant+Giza',
                'image' => null,
                'phone' => '+20 2 3386 1234',
                'opening_hours' => '8:00 AM – 10:00 PM',
            ],
            [
                'name' => 'Andrea El Mariouteya',
                'description' => 'Famous for grilled chicken and Egyptian country-style dining in a garden setting near the Pyramids.',
                'address' => 'Mariouteya St, Haram, Giza',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.3,
                'region' => 'Giza',
                'lat' => 29.9875,
                'lng' => 31.1458,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Andrea+El+Mariouteya+Giza',
                'image' => null,
                'phone' => '+20 2 3386 5573',
                'opening_hours' => '12:00 PM – 11:00 PM',
            ],
            // ─── Alexandria ──────────────────────────────────────────
            [
                'name' => 'Mohamed Ahmed Restaurant',
                'description' => 'Alexandria icon since 1950, renowned for its ful, falafel, and Egyptian breakfast — a must-visit.',
                'address' => '22 Saad Zaghloul St, Alexandria',
                'category' => 'Egyptian',
                'price_level' => '$',
                'rating' => 4.4,
                'region' => 'Alexandria',
                'lat' => 31.2018,
                'lng' => 29.9153,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Mohamed+Ahmed+Restaurant+Alexandria',
                'image' => null,
                'phone' => '+20 3 487 3576',
                'opening_hours' => '6:00 AM – 12:00 AM',
            ],
            [
                'name' => 'Fish Market',
                'description' => 'Alexandria premier seafood restaurant right on the Corniche — pick your fresh catch and they grill it.',
                'address' => 'Corniche, Alexandria',
                'category' => 'Seafood',
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Alexandria',
                'lat' => 31.2050,
                'lng' => 29.9120,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Fish+Market+Alexandria+Corniche',
                'image' => 'https://images.unsplash.com/photo-1579632652768-6cb9eb4afc26',
                'phone' => '+20 3 480 5114',
                'opening_hours' => '12:00 PM – 11:00 PM',
            ],
            [
                'name' => 'Balbaa Restaurant',
                'description' => 'Alexandria oldest seafood institution since 1948, famous for its fried fish, shrimp, and calamari with secret spice blends.',
                'address' => '15 El-Gaish Rd, Al-Manshiya, Alexandria',
                'category' => 'Seafood',
                'price_level' => '$$',
                'rating' => 4.5,
                'region' => 'Alexandria',
                'lat' => 31.1970,
                'lng' => 29.9020,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Balbaa+Restaurant+Alexandria',
                'image' => null,
                'phone' => '+20 3 486 0042',
                'opening_hours' => '10:00 AM – 11:00 PM',
            ],
            [
                'name' => 'Ibrahim Ibrahim Restaurant',
                'description' => 'Hidden gem in Alexandria old quarter known for its fresh seafood platters and traditional Egyptian fish dishes.',
                'address' => '16 Sheikh El-Barsa St, Anfoushi, Alexandria',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.3,
                'region' => 'Alexandria',
                'lat' => 31.2090,
                'lng' => 29.8850,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Ibrahim+Ibrahim+Restaurant+Alexandria',
                'image' => null,
                'phone' => '+20 3 481 0360',
                'opening_hours' => '11:00 AM – 10:00 PM',
            ],
            [
                'name' => 'Santorini Greek Restaurant',
                'description' => 'Authentic Greek restaurant perched on the Corniche with blue-and-white Cycladic decor and stunning Mediterranean views.',
                'address' => 'Corniche, Alexandria',
                'category' => 'Greek',
                'price_level' => '$$$',
                'rating' => 4.4,
                'region' => 'Alexandria',
                'lat' => 31.2060,
                'lng' => 29.9100,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Santorini+Greek+Restaurant+Alexandria',
                'image' => null,
                'phone' => '+20 3 480 5030',
                'opening_hours' => '12:00 PM – 12:00 AM',
            ],
            // ─── Luxor ──────────────────────────────────────────────
            [
                'name' => 'Sofra Restaurant & Café',
                'description' => 'Beautifully restored colonial house serving authentic Egyptian and Middle Eastern cuisine in Luxor.',
                'address' => 'Sharia Mohamed Farid, Luxor',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.6,
                'region' => 'Luxor',
                'lat' => 25.6872,
                'lng' => 32.6396,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Sofra+Restaurant+Luxor',
                'image' => null,
                'phone' => '+20 95 235 9752',
                'opening_hours' => '11:00 AM – 11:00 PM',
            ],
            [
                'name' => 'Al-Sahaby Lane Restaurant',
                'description' => 'Rooftop restaurant overlooking Luxor Temple — serves Egyptian, Mediterranean, and international dishes.',
                'address' => 'Al-Sahaby Lane, Luxor',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.5,
                'region' => 'Luxor',
                'lat' => 25.6833,
                'lng' => 32.6389,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Al+Sahaby+Lane+Restaurant+Luxor',
                'image' => null,
                'phone' => '+20 100 527 8888',
                'opening_hours' => '7:00 AM – 11:00 PM',
            ],
            [
                'name' => 'The Lantern Restaurant',
                'description' => 'Intimate garden restaurant in Luxor serving authentic Egyptian home-style cooking and traditional mezza platters.',
                'address' => 'St. Joseph St, Luxor',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.5,
                'region' => 'Luxor',
                'lat' => 25.6850,
                'lng' => 32.6405,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Lantern+Restaurant+Luxor',
                'image' => null,
                'phone' => '+20 95 236 1567',
                'opening_hours' => '11:00 AM – 10:00 PM',
            ],
            [
                'name' => '1886 Restaurant',
                'description' => 'Fine-dining restaurant inside the historic Winter Palace Hotel with grand colonial ambiance and European-Egyptian fusion.',
                'address' => 'Winter Palace Hotel, Corniche, Luxor',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.6,
                'region' => 'Luxor',
                'lat' => 25.6835,
                'lng' => 32.6420,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=1886+Restaurant+Winter+Palace+Luxor',
                'image' => null,
                'phone' => '+20 95 238 0425',
                'opening_hours' => '7:00 PM – 11:00 PM',
            ],
            [
                'name' => 'El Mesala Restaurant',
                'description' => 'Rooftop restaurant with breathtaking views of the Nile and Luxor Temple, serving Egyptian and Oriental cuisine.',
                'address' => 'New Corniche, Luxor',
                'category' => 'Egyptian',
                'price_level' => '$$',
                'rating' => 4.3,
                'region' => 'Luxor',
                'lat' => 25.6860,
                'lng' => 32.6380,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=El+Mesala+Restaurant+Luxor',
                'image' => null,
                'phone' => '+20 95 237 2345',
                'opening_hours' => '11:00 AM – 11:00 PM',
            ],
            // ─── Aswan ──────────────────────────────────────────────
            [
                'name' => 'Nubian House Restaurant',
                'description' => 'Traditional Nubian dining experience on Elephantine Island with local music and river views.',
                'address' => 'Elephantine Island, Aswan',
                'category' => 'Nubian',
                'price_level' => '$$',
                'rating' => 4.6,
                'region' => 'Aswan',
                'lat' => 24.0889,
                'lng' => 32.8897,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Nubian+House+Restaurant+Aswan',
                'image' => null,
                'phone' => '+20 97 231 4646',
                'opening_hours' => '12:00 PM – 10:00 PM',
            ],
            [
                'name' => 'Chef Khalil',
                'description' => 'Family-run Aswan favorite for authentic Nubian and Egyptian dishes — famous for its grilled chicken and tagines.',
                'address' => 'Sharia Al Souk, Aswan',
                'category' => 'Egyptian',
                'price_level' => '$',
                'rating' => 4.4,
                'region' => 'Aswan',
                'lat' => 24.0900,
                'lng' => 32.8980,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Chef+Khalil+Aswan',
                'image' => null,
                'phone' => '+20 97 231 3005',
                'opening_hours' => '8:00 AM – 11:00 PM',
            ],
            [
                'name' => 'El-Masry Restaurant',
                'description' => 'No-frills Aswan institution serving some of the best grilled chicken, kofta, and ful in town since the 1970s.',
                'address' => 'Sharia Al Souk, Aswan',
                'category' => 'Egyptian',
                'price_level' => '$',
                'rating' => 4.2,
                'region' => 'Aswan',
                'lat' => 24.0895,
                'lng' => 32.8970,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=El+Masry+Restaurant+Aswan',
                'image' => null,
                'phone' => '+20 97 231 4111',
                'opening_hours' => '7:00 AM – 11:00 PM',
            ],
            [
                'name' => 'Panorama Restaurant & Bar',
                'description' => 'Stunning rooftop terrace with panoramic Nile views at the Old Cataract Hotel, serving international fine-dining.',
                'address' => 'Old Cataract Hotel, Aswan',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.7,
                'region' => 'Aswan',
                'lat' => 24.0860,
                'lng' => 32.8850,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Panorama+Restaurant+Old+Cataract+Aswan',
                'image' => null,
                'phone' => '+20 97 231 6000',
                'opening_hours' => '6:00 PM – 11:00 PM',
            ],
            // ─── Hurghada ────────────────────────────────────────────
            [
                'name' => 'Starfish Restaurant',
                'description' => 'Popular Red Sea seafood spot with fresh catches daily, grilled to perfection, right by the marina.',
                'address' => 'Hurghada Marina, Hurghada',
                'category' => 'Seafood',
                'price_level' => '$$',
                'rating' => 4.4,
                'region' => 'Hurghada',
                'lat' => 27.2278,
                'lng' => 33.8406,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Starfish+Restaurant+Hurghada',
                'image' => null,
                'phone' => '+20 65 346 5001',
                'opening_hours' => '12:00 PM – 11:00 PM',
            ],
            [
                'name' => 'The Grill House',
                'description' => 'Steakhouse and grill specializing in prime cuts, BBQ ribs, and hearty sides in a relaxed atmosphere.',
                'address' => 'Sheraton Rd, Hurghada',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.3,
                'region' => 'Hurghada',
                'lat' => 27.2250,
                'lng' => 33.8380,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=The+Grill+House+Hurghada',
                'image' => null,
                'phone' => '+20 65 344 9770',
                'opening_hours' => '1:00 PM – 12:00 AM',
            ],
            [
                'name' => 'El Dar Darek',
                'description' => 'Authentic Lebanese restaurant in Hurghada serving generous mezze platters, grilled meats, and fresh tabbouleh.',
                'address' => 'El Mamsha, Hurghada',
                'category' => 'Lebanese',
                'price_level' => '$$',
                'rating' => 4.3,
                'region' => 'Hurghada',
                'lat' => 27.2300,
                'lng' => 33.8420,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=El+Dar+Darek+Hurghada',
                'image' => null,
                'phone' => '+20 65 345 1002',
                'opening_hours' => '12:00 PM – 12:00 AM',
            ],
            [
                'name' => 'Moby Dick Restaurant',
                'description' => 'Hurghada best seafood restaurant with a lively atmosphere, fresh Red Sea catches, and harbour views from the terrace.',
                'address' => 'Hurghada Marina, Hurghada',
                'category' => 'Seafood',
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Hurghada',
                'lat' => 27.2285,
                'lng' => 33.8410,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Moby+Dick+Hurghada+Marina',
                'image' => null,
                'phone' => '+20 65 346 3456',
                'opening_hours' => '11:00 AM – 11:00 PM',
            ],
            [
                'name' => "Jaggy's Restaurant",
                'description' => 'Popular international restaurant in Hurghada known for its diverse menu, live cooking, and family-friendly vibe.',
                'address' => 'Sheraton Rd, Hurghada',
                'category' => 'International',
                'price_level' => '$$',
                'rating' => 4.2,
                'region' => 'Hurghada',
                'lat' => 27.2260,
                'lng' => 33.8390,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Jaggys+Restaurant+Hurghada',
                'image' => null,
                'phone' => '+20 65 344 5678',
                'opening_hours' => '10:00 AM – 12:00 AM',
            ],
            // ─── Sharm El-Sheikh ─────────────────────────────────────
            [
                'name' => 'Fares Seafood Restaurant',
                'description' => 'Best seafood in Sharm El-Sheikh — choose your fish from the display and enjoy it grilled or fried.',
                'address' => 'Naama Bay, Sharm El-Sheikh',
                'category' => 'Seafood',
                'price_level' => '$$',
                'rating' => 4.5,
                'region' => 'Sharm El-Sheikh',
                'lat' => 27.9158,
                'lng' => 34.3294,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Fares+Seafood+Sharm+El+Sheikh',
                'image' => null,
                'phone' => '+20 69 360 2008',
                'opening_hours' => '11:00 AM – 11:00 PM',
            ],
            [
                'name' => 'Pirates Bar & Restaurant',
                'description' => 'Lively spot in Naama Bay serving pizza, pasta, grilled meats, and cocktails with live entertainment.',
                'address' => 'Naama Bay, Sharm El-Sheikh',
                'category' => 'International',
                'price_level' => '$$',
                'rating' => 4.2,
                'region' => 'Sharm El-Sheikh',
                'lat' => 27.9140,
                'lng' => 34.3280,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Pirates+Bar+Naama+Bay+Sharm',
                'image' => null,
                'phone' => '+20 69 360 1400',
                'opening_hours' => '10:00 AM – 2:00 AM',
            ],
            [
                'name' => 'Il Mercato',
                'description' => 'Authentic Italian trattoria in Sharm El-Sheikh serving wood-fired pizzas, homemade pasta, and classic gelato.',
                'address' => 'Naama Bay, Sharm El-Sheikh',
                'category' => 'Italian',
                'price_level' => '$$',
                'rating' => 4.3,
                'region' => 'Sharm El-Sheikh',
                'lat' => 27.9160,
                'lng' => 34.3300,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Il+Mercato+Naama+Bay+Sharm',
                'image' => null,
                'phone' => '+20 69 360 3300',
                'opening_hours' => '12:00 PM – 11:30 PM',
            ],
            [
                'name' => 'The Lebanese House',
                'description' => 'Award-winning Lebanese restaurant in Sharm offering authentic mezze, grilled kebabs, and freshly baked bread.',
                'address' => 'Naama Bay, Sharm El-Sheikh',
                'category' => 'Lebanese',
                'price_level' => '$$',
                'rating' => 4.4,
                'region' => 'Sharm El-Sheikh',
                'lat' => 27.9110,
                'lng' => 34.3270,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=The+Lebanese+House+Sharm+El+Sheikh',
                'image' => null,
                'phone' => '+20 69 360 2121',
                'opening_hours' => '12:00 PM – 12:00 AM',
            ],
            [
                'name' => 'La Veranda',
                'description' => 'Elegant international restaurant in Sharm with garden seating, serving French-Mediterranean fusion cuisine.',
                'address' => 'Ras Nasrani, Sharm El-Sheikh',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Sharm El-Sheikh',
                'lat' => 27.9230,
                'lng' => 34.3420,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=La+Veranda+Sharm+El+Sheikh',
                'image' => null,
                'phone' => '+20 69 362 0020',
                'opening_hours' => '6:00 PM – 11:00 PM',
            ],
            // ─── El Gouna ───────────────────────────────────────────
            [
                'name' => 'Zaitouna Restaurant',
                'description' => 'Beachfront dining on El Gouna lagoon serving Mediterranean cuisine, fresh seafood, and signature cocktails at sunset.',
                'address' => 'El Gouna, Hurghada',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.5,
                'region' => 'Hurghada',
                'lat' => 27.3780,
                'lng' => 33.6860,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Zaitouna+El+Gouna',
                'image' => null,
                'phone' => '+20 65 358 0050',
                'opening_hours' => '12:00 PM – 12:00 AM',
            ],
            [
                'name' => 'Casa Cook Restaurant',
                'description' => 'Relaxed poolside dining at Casa Cook El Gouna with a Mediterranean menu focused on wood-fired cooking and fresh salads.',
                'address' => 'Casa Cook Hotel, El Gouna, Hurghada',
                'category' => 'International',
                'price_level' => '$$$',
                'rating' => 4.4,
                'region' => 'Hurghada',
                'lat' => 27.3800,
                'lng' => 33.6880,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Casa+Cook+Restaurant+El+Gouna',
                'image' => null,
                'phone' => '+20 65 358 0300',
                'opening_hours' => '7:00 AM – 11:00 PM',
            ],
            // ─── Dahab ──────────────────────────────────────────────
            [
                'name' => 'Bamboo Shoot Restaurant',
                'description' => 'Famous Dahab restaurant serving Thai, Chinese, and Egyptian dishes in a laid-back Bedouin-style beach setting.',
                'address' => 'Lighthouse Area, Dahab',
                'category' => 'Asian',
                'price_level' => '$$',
                'rating' => 4.3,
                'region' => 'Dahab',
                'lat' => 28.4960,
                'lng' => 34.5150,
                'google_maps_url' => 'https://www.google.com/maps/search/?api=1&query=Bamboo+Shoot+Restaurant+Dahab',
                'image' => null,
                'phone' => '+20 69 364 0322',
                'opening_hours' => '10:00 AM – 11:00 PM',
            ],
        ];

        foreach ($restaurants as $data) {
            Restaurant::updateOrCreate(
                ['name' => $data['name'], 'address' => $data['address']],
                $data,
            );
        }
    }
}
